### DISCUSSION TITLE
CSS Styling help (layout cards)

### DISCUSSION THREAD

**Discussion by tocri** [microsoft-search/pnp-modern-search#3705] [Q&A] [answered]
Hi, 

I have some issues with Css Styling.
I have added a custom css to the keywords field 

```scss
<style>
    .view-count-container {
        display: flex;
        align-items: center;
        margin-top: 0px;
        padding-top: 0px;
        margin-bottom:0px;
    }
    .view-count-container i { 
        margin-right: 5px; /* Espace entre l'icône et le nombre de vues */
        margin-bottom:0pc;
    }
    .view-count-container span {
        text-decoration: none; /* Retire le soulignement, changez si désiré */
        margin-right: 0px; /* Espace à droite, ajustez si nécessaire */
        margin-bottom:0px;
    }
</style>

{{#if (slot item @root.slots.ViewCount)}}
    <div class="view-count-container">
        <pnp-icon data-name="View" aria-hidden="true" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-icon>
        <span>{{slot item @root.slots.ViewCount}}</span>
    </div>
{{/if}}


<style>
    .comment-count-container {
        display: flex;
        align-items: center;
        margin-top: 0;
        padding-top: 0;
		margin-bottom:0px;
    }
    .comment-count-container i { 
        margin-right: 5px; /* Espace entre l'icône et le nombre de vues */
		margin-bottom:0px;
    }
    .comment-count-container span {
        text-decoration: none; /* Retire le soulignement, changez si désiré */
        margin-right: auto; /* Espace à droite, ajustez si nécessaire */
		margin-bottom:0px;
    }
</style>

{{#if (slot item @root.slots.CommentCount)}}
    <div class="comment-count-container">
        <pnp-icon data-name="comment" aria-hidden="true" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-icon>
        <span>{{slot item @root.slots.CommentCount}}</span>
    </div>
{{/if}}`
``` 

![image](https://github.com/microsoft-search/pnp-modern-search/assets/10110260/553dd58a-0aed-408d-88b8-1aaaeb5124c4)

Is it possible to have the comment count besides view count ?

Thank you

**Comment by tocri** [comment, marked as answer]
Ok i've found it

```scss
<style>
    .icon-container {
        display: flex; /* Utilise Flexbox pour l'affichage */
        align-items: center; /* Centre les éléments verticalement */
        justify-content: flex-start; /* Alignement horizontal au début */
    }
    .icon-container i {
	margin-right: 5px
	}
    .icon-container span {
        margin-right: 10px; /* Espace entre les éléments, ajustez selon les besoins */
        margin-bottom: 0; /* Assurez-vous qu'il n'y a pas de marge inférieure */
    }
    /* Supprimez les marges supplémentaires ou paddings si nécessaire */
    .icon-container .pnp-icon:last-child,
    .icon-container span:last-child {
        margin-right: 0; /* Pas de marge à droite pour le dernier élément */
    }
</style>

<div class="icon-container">
    {{#if (slot item @root.slots.ViewCount)}}
        <pnp-icon data-name="View" aria-hidden="true" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-icon>
        <span>{{slot item @root.slots.ViewCount}}</span>
    {{/if}}
    {{#if (slot item @root.slots.CommentCount)}}
        <pnp-icon data-name="Comment" aria-hidden="true" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-icon>
        <span>{{slot item @root.slots.CommentCount}}</span>
    {{/if}}
</div>

``` 




![image](https://github.com/microsoft-search/pnp-modern-search/assets/10110260/75f0f1da-775f-4f20-8bd1-5408a99dd9d4)
