### DISCUSSION TITLE
Remove Heading Space in Details List When Using Groups

### DISCUSSION THREAD

**Discussion by dontthroworanges** [microsoft-search/pnp-modern-search#4148] [Q&A] [answered]
Is it possible to remove the highlighted space in the Details List header when using groups? My OCD would appreciate the fileicon lining up with the text in the row below. :)

![image](https://github.com/user-attachments/assets/5419d728-d06c-4b09-974c-14fcb6e2de9e)

**Comment by patrikhellgren** [comment]
Could you give a description on how you configured the webpart? This is how it looks for me after setting up a simple default configuration:

![image](https://github.com/user-attachments/assets/727afe47-731e-483f-a3a1-8b9059e8401d)

**Reply by dontthroworanges** [reply]
Hi @patrikhellgren, 
In your test case, are you adding any additional group by fields? I have two additional to provide a cascaded layout. 

![image](https://github.com/user-attachments/assets/9b1621a8-7e3c-41e8-a0e5-524ca2fb9388)

**Comment by patrikhellgren** [comment, marked as answer]
Ahh, I see, after adding another group level I get the same. That is how the Fluent UI DetailsList displays the header after grouping because of where the items are displayed after expanding the groups down to the item level and the spacing becomes wider for each level you add.

![image](https://github.com/user-attachments/assets/28816cea-0dd8-46dd-b182-c675f6b1c398)

That is also how I would prefer it, having the file icons in line with the icon in the header.

If you really want the spacing removed you can just modify the Details list layout and add the following at the bottom of the top style section:

```css
        .template .ms-GroupSpacer {
            display: none !important;
        }
```

That would of course make the groups not being indented when expanding them.
If you would rather have the groups indented like default you could add this instead but that looks a bit weird after expanding the groups down to the item level:

```css
        .template .ms-DetailsList-headerWrapper .ms-GroupSpacer {
            display: none !important;
        }
```

**Reply by dontthroworanges** [reply]
Thanks @patrikhellgren! The second option you provided is exactly what I was looking for. :)

**Comment by dontthroworanges** [comment]
@patrikhellgren Sorry last question that may be related? Every time I reload the page, the horizontal scroll bar appears in the web part and then disappears once any one of the groups is expanded. Is there a way to not show the scroll bar? (assuming that the content is not wider than the web part)

![image](https://github.com/user-attachments/assets/c2b1fb8e-d555-49f7-813d-9b4399eb7837)

**Reply by patrikhellgren** [reply]
That has to do with the width of your columns and there is a known bug in Fluent UI around this which we have to wait for a fix for. In the meantime if you want to hide the scrollbar (which could affect the scrolling behaviour) you could add this in the same place as the other css tags:

```css
        .template .ms-DetailsList {
            overflow-x: hidden !important;
        }
```
